### ISSUE TITLE
Entry Point here?

### ISSUE THREAD

**Issue by Droidtown** [Droidtown/AItlas#3]
這裡該有個程式進入點吧？

https://github.com/Droidtown/AItlas/blob/45368d572b93994b23f3090b63a647736ffe5fb4/tools/ArticutDemo_cathy5.0.py#L130C1-L130C1

**Comment by shendongCathy** [comment]
> 這裡該有個程式進入點吧？
> 
> https://github.com/Droidtown/AItlas/blob/45368d572b93994b23f3090b63a647736ffe5fb4/tools/ArticutDemo_cathy5.0.py#L130C1-L130C1

Sorry, I don't quite understand what the entry point is.
Is that the function(x, y) as the following?
```run_get_verbs(23000, 24000)```

**Comment by shendongCathy** [comment]
I plan not to call **loki** to insert sentences with _danlen_ but  insert them manually instead.

**Comment by shendongCathy** [comment]
> I plan not to call **loki** to insert sentences with _danlen_ but insert them manually instead.

BTW, manually operation is not a quite sensible in this era. Thus, I would save them while think about how to fix the previous problem
