### ISSUE TITLE
In line 41, sometimes it appears the "KeyError" in the tab of  Exceptions.

### ISSUE THREAD

**Issue by shendongCathy** [Droidtown/AItlas#4]
https://github.com/Droidtown/AItlas/blob/4d53919677e800b2744ef6ec89fe7b0c83c2ebf7/tools/ArticutDemo_cathy5.0.py#L41

<img width="1440" alt="截圖 2023-07-24 07 49 36" src="https://github.com/Droidtown/AItlas/assets/99934754/86bdf304-bb01-4aaa-9431-d88043865ebb">

從上圖，我發現
1. 之前檔案person_classifier沒有辦法把人名其他的過濾乾淨(針對這個問題，Ｉam trying.)

後來，有一兩次遇到這個問題，我又就再重跑一次，又沒有這個問題了。 不知道為什麼？

結果，我從stack data 看到這個訊息：{'status': False, 'msg': 'Requests per minute exceeded! Each account can only issue 80 requests ... (truncated) ，恍然大悟了....

**Comment by shendongCathy** [comment]
剛看了自己上傳的person_classifier的檔案，覺得我自己錯的很離譜，我得改一改～

**Comment by Droidtown** [comment]
> 之前檔案person_classifier沒有辦法把人名其他的過濾乾淨
這個問題有找到原因嗎？

>後來，有一兩次遇到這個問題，我又就再重跑一次，又沒有這個問題了。 不知道為什麼？
resultDICT 是透過網路 API 來的，而透過網路 API 而來的可能情況很多，所以你要提供 Error Message，不然我也沒辦法猜出來是出了什麼問題。

**Comment by shendongCathy** [comment]
> 結果，我從stack data 看到這個訊息：{'status': False, 'msg': 'Requests per minute exceeded! Each account can only issue 80 requests ... (truncated) ，恍然大悟了....
